Repository ericahagle/ideabox, pull requests merged in 2023-09, with the labels that each got.

#33 refactor: Clean up some code that got messed up during merge conflicts
  main.js
  styles.css
Labels: bug

#41 Include a filter button
  index.html
  styles.css
Labels: user story

#34 feat: Add Favorite Buttons to New Ideas
  assets/star-active.svg
  assets/star.svg
  index.html
  main.js
  styles.css
Labels: user story

#42 feat: Add Fave Functionality
  main.js
Labels: user story

#51 refactor: Clean up some code, including function to toggle fave button
  main.js
Labels: enhancement

#52 fix: Address sidebar issue when more than 3 ideas are loaded
  styles.css
Labels: bug

#53 Add a limit to the character length for title and body input fields
  index.html
  main.js
Labels: enhancement

#55 docs: Update README add screen shot
  README.md
  assets/ideabox.png
Labels: documentation

#56 refactor: Clean up code formatting and remove unnecessary comments
  main.js
  styles.css
Labels: enhancement
